"""Database

Revision ID: 0cfe177c5fc9
Revises: 2ddcca399542
Create Date: 2023-04-30 03:12:54.395789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfe177c5fc9'
down_revision = '2ddcca399542'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
