"""Init

Revision ID: 161ebffe8c4c
Revises: ee1137d204ce
Create Date: 2023-05-10 01:37:42.171124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161ebffe8c4c'
down_revision = 'ee1137d204ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
