"""Database

Revision ID: 2a6cafda4c3a
Revises: c26656f03fa0
Create Date: 2023-04-30 03:24:34.682413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6cafda4c3a'
down_revision = 'c26656f03fa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
