"""Database

Revision ID: 2ddcca399542
Revises: 42a19270205b
Create Date: 2023-04-29 17:41:10.470458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ddcca399542'
down_revision = '42a19270205b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('university_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_foreign_key(None, 'user', 'university', ['university_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'university_id')
    op.drop_table('university')
    # ### end Alembic commands ###
