"""Database

Revision ID: 36e9022b41ab
Revises: ad0165ea4fa0
Create Date: 2023-04-30 12:49:21.006548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e9022b41ab'
down_revision = 'ad0165ea4fa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
