"""Database

Revision ID: 42a19270205b
Revises: c0786c4c23e1
Create Date: 2023-04-28 03:28:30.583897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '42a19270205b'
down_revision = 'c0786c4c23e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_student_id', table_name='user')
    op.drop_column('user', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_user_student_id', 'user', ['student_id'], unique=False)
    # ### end Alembic commands ###
