"""Init

Revision ID: 45f3aec45e2d
Revises: f018909980d2
Create Date: 2023-05-05 14:09:20.327658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f3aec45e2d'
down_revision = 'f018909980d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
