"""Init

Revision ID: 60d661c24071
Revises: 45f3aec45e2d
Create Date: 2023-05-05 15:45:28.855714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d661c24071'
down_revision = '45f3aec45e2d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
