"""Init

Revision ID: 69756ebad521
Revises: f2a4e2a55fe5
Create Date: 2023-05-06 18:35:16.380233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69756ebad521'
down_revision = 'f2a4e2a55fe5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
