"""Init

Revision ID: 73d3acbaef9c
Revises: 60d661c24071
Create Date: 2023-05-05 15:50:58.365326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d3acbaef9c'
down_revision = '60d661c24071'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
