"""Init

Revision ID: 8806ce1bbb59
Revises: ba2c4d5202b5
Create Date: 2023-05-05 01:43:38.001773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8806ce1bbb59'
down_revision = 'ba2c4d5202b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
