"""Init

Revision ID: ae6e7ba73ec9
Revises: 161ebffe8c4c
Create Date: 2023-05-10 02:15:25.921595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6e7ba73ec9'
down_revision = '161ebffe8c4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
