"""Database

Revision ID: ba2c4d5202b5
Revises: 36e9022b41ab
Create Date: 2023-04-30 12:52:15.074908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2c4d5202b5'
down_revision = '36e9022b41ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
