"""Database

Revision ID: c26656f03fa0
Revises: f89b23c183fd
Create Date: 2023-04-30 03:17:58.703792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26656f03fa0'
down_revision = 'f89b23c183fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
