"""Init

Revision ID: f018909980d2
Revises: 8806ce1bbb59
Create Date: 2023-05-05 14:09:05.075271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f018909980d2'
down_revision = '8806ce1bbb59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
